SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
DROP TABLE IF EXISTS `%USER_TABLE_NAME%.tmp`;
CREATE TABLE IF NOT EXISTS `%USER_TABLE_NAME%.tmp` (
  `UUID` varchar(64) NOT NULL,
  `EMAIL` varchar(128) NOT NULL,
  `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `%USER_TABLE_NAME%`;
CREATE TABLE IF NOT EXISTS `%USER_TABLE_NAME%` (
  `UUID` varchar(64) NOT NULL,
  `EMAIL` varchar(128) NOT NULL,
  `PASSWORD` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `PRIVILEGE` int(11) NOT NULL DEFAULT '0',
  `LAST_CONNECTION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,    
  
  -- CUSTONIZABLE PART
  
     -- This actually just an example, of additionnal field
    `FIRSTNAME` varchar(128),
  
  -- /CUSTONIZABLE  
  
  PRIMARY KEY (`UUID`,`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;